#!/usr/bin/env bash

set -e

. scripts/env.sh

# Run a command into the chrooted target FS using qemu and proot
run_in_qemu()
{
    proot -0 -r $SYSROOT -q qemu-$ARCH-static -b /etc/resolv.conf -b /etc/mtab -b /proc -b /sys $*
}

if [ ! -e $SYSROOT ]; then
    error "Directory $SYSROOT does not exist. Run ./scripts/download-rootfs to download a fresh image."
    exit 1
fi

. scripts/distro/prepare-$DISTRO

mkdir -p $SYSROOT/$NV_PREFIX
mkdir -p $SYSROOT/boot
mkdir -p $SYSROOT/lib/modules
mkdir -p $SYSROOT/lib/firmware

status "Adding environment to /etc/profile.d/nouveau.sh"
cat <<EOF |tee $SYSROOT/etc/profile.d/nouveau.sh >/dev/null
export PATH="$NV_PREFIX/bin:\$PATH"
export PKG_CONFIG_PATH="$NV_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
EOF

status "Adding ld.so.conf.d entry for $NV_PREFIX/lib"
cat <<EOF |tee $SYSROOT/etc/ld.so.conf.d/nouveau.conf >/dev/null
$NV_PREFIX/lib
EOF

status "Enabling Xwayland in Weston configuration"
mkdir -p $SYSROOT/etc/xdg/weston
cat <<EOF >$SYSROOT/etc/xdg/weston/weston.ini
[core]
modules=xwayland.so

[xwayland]
path=/opt/nouveau/bin/Xwayland
EOF

status "Target FS ready to compile the open graphics stack!"
